### ISSUE TITLE
Unable to get balance

### ISSUE THREAD

**Issue by Realmm** [enjin/enjin-java-sdk#70]
Trying to make a GetBalances request, the fields have been set properly. This issue refers to using `2.0.0-alpha.2` version. The `2.0.0-alpha.4` master branch currently does not authenticate my project properly, so I can't seem to use that - but that's seperate to what this issue is about.

```
        GetBalances req = new GetBalances()
                .filter(new BalanceFilter()
                        .projectUuid(<uuid>)
                        .valueIs(Operator.GREATER_THAN)
                        .value(0)
                        .wallet(ethAddress));
```
To explain the issue a bit more, whenever `.projectUuid(String)` or `.projectUuidIn(String...)` are used, the following error gets thrown
When I exclude the projectUuid, the request gets sent fine, but I apparently have 0 balance even though I have 2 of the same type of asset (an NFT minted) in my wallet, and it should be showing a balance here I would assume. All fields parsed in are accurate, so the request as far as I can tell on my end is fine, but the error still occurs. 

So there are 2 issues, 1. is the balance projectUuid and projectUuidIn fields not being able to be set, and 2. I am getting 0 balance from any variation of the request I try to make (that is successful), so I can't tell how many of an NFT someone has. 

(Note GraphQLError is a custom error - you guys have implemented it though in EnjinCraft, error should explain the issue)
```
GraphQLError(message=Variable "$filter" got invalid value {"projectUuid":"<uuid>","wallet":"<wallet>","value":0,"value_is":"GREATER_THAN"}; Field "projectUuid" is not defined by type BalanceFilter., code=400, locations=null, details=null)
	at enjin.schemas.BaseSchema$1.onResponse(BaseSchema.java:150) 
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) 
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) 
	at java.lang.Thread.run(Thread.java:831) 
```

**Comment by BishopJohnson** [comment]
Hi @Realmm,

After talking with our platform team, the project UUID related arguments for `BalanceFilter` have been removed from the v2 alpha schemas and as such will be removed from the v2 SDK as well in an upcoming release. Additionally, to my knowledge there may be an outstanding bug with the `value_is` operator that may be the cause of missing balance results that are otherwise expected. This has been communicated with the platform team to look into.

You also mentioned EnjinCraft and I was wondering if you're using the v2 Java SDK inside of it? As currently EnjinCraft only uses the Java SDK designed for the v1 platform API.
